server:
  port: 8000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedMethods:
              - GET
              - POST
              - DELETE
              - PUT
              - OPTIONS
            allowedOrigins:
              - "http://localhost:3000"
            allowedHeaders: "*"
      default-filters:
        - name : GlobalFilter
          args:
            baseMessage: hello-world
            preLogger: false
            postLogger: true
      routes:
        - id: login-service
          uri: lb://LOGIN-SERVICE
          predicates:
            - Path= /login/**
          filters:
            - CustomFilter

management:
  endpoints:
    enabled: true
    web:
      exposure:
        include: gateway, routes, refresh, health, beans, httpstrace
