server:
  port: 8000

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedMethods:
              - GET
              - POST
              - DELETE
              - PUT
              - OPTIONS
            allowedOrigins:
              - "http://localhost:3000"
            allowedHeaders: "*"
      routes:
        - id: login-service
          uri: lb://LOGIN-SERVICE
          predicates:
            - Path= /user/**
          filters:
            - CustomFilter
            - LoggingFilter
        - id: contract-coa-service
          uri: lb://CONTRACT-COA-SERVICE
          predicates:
            - Path= /coa/**
          filters:
            - CustomFilter
        - id: contract-member-service
          uri: lb://CONTRACT-COA-SERVICE
          predicates:
            - Path= /contract/**
          filters:
            - CustomFilter

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    enabled: true
    web:
      exposure:
        include: gateway, routes, refresh, health, beans, httpstrace
